language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
# command to install dependencies
install:
  - pip install . --use-mirrors
  - pip install nose coverage tissue coveralls --use-mirrors
# command to run tests
script:
    - nosetests --with-coverage

after_success:
    - coveralls

